a = list("紅豆生南國，春來發幾枝？願君多采擷，此物最相思。")
b = list("春眠不覺曉，處處聞啼鳥。夜來風雨聲，花落知多少。")
a.remove("，")
a.remove("，")
a.remove("。")
a.remove("？")
b.remove("，")
b.remove("，")
b.remove("。")
b.remove("。")
a1 = set(a)
b1 = set(b)
print(a1 & b1)